notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

jdk:
  - oraclejdk8

scala:
  - 2.12.1

install: true

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
